### ISSUE TITLE
upload not working

### ISSUE THREAD

**Issue by jafrazie** [CiscoDevNet/yang-explorer#27]
Local not working either, but here's an example of uploading from git.

ubuntu@jafrazie-ubuntu1:~/yang-explorer/server$ python manage.py bulkupload --user guest --git https://github.com/CiscoDevNet/xe-netconf-yang/
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/yang-explorer/server/explorer/management/commands/bulkupload.py", line 27, in <module>
    from explorer.utils.uploader import sync_file, commit_files
  File "/home/ubuntu/yang-explorer/server/explorer/utils/uploader.py", line 22, in <module>
    from explorer.utils.yang import Parser, Compiler
  File "/home/ubuntu/yang-explorer/server/explorer/utils/yang.py", line 24, in <module>
    from explorer.utils.dygraph import DYGraph
  File "/home/ubuntu/yang-explorer/server/explorer/utils/dygraph.py", line 19, in <module>
    from graphviz import Digraph
ImportError: No module named graphviz

**Comment by pgohite** [comment]
Correct Commands to upload git models from command line:

Make sure you have latest yang explorer (optional)
$ git stash
$ git pull origin
$ git stash apply

Make sure all dependencies are installed
$ bash setup.sh
  
Activate Virtualenv
$ cd <install-root>/yang-explorer
$ **source v/bin/activate**
$ cd server

Start Upload
$ **python manage.py bulkupload --user guest --git https://github.com/CiscoDevNet/xe-netconf-yang.git --dir models/Yang-Explorer-Models/**

Deactivate virtualenv
$ deactivate

Start yang-explorer server
$ cd <install-root>/yang-explorer
$ bash start.sh

**Comment by pgohite** [comment]
Verified using above instructions.
