### ISSUE TITLE
Does this project support JunOS devices.

### ISSUE THREAD

**Issue by sachinsr099** [CiscoDevNet/yang-explorer#34]
I am trying to work on Junos supported devices like MX 240.

During the Device profile requirements. I chose "others" in the Platform form.

While trying to fetch Yang Models from the "Manage Models" section I got this error "Something went wrong, returned errored response" 

------------------------------------------------------------------------------------------------------------------
[25/Jul/2016 23:48:17] ERROR [django.request] Internal Server Error: /explorer/schema
Traceback (most recent call last):
  File "/Users/sachin_sr/Downloads/yang-explorer-master/v/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/views.py", line 281, in schema_handler
    return get_schema(request, req)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/utils/schema.py", line 78, in get_schema
    sclist = xml[0][0][0][0]
  File "lxml.etree.pyx", line 1098, in lxml.etree._Element.__getitem__ (src/lxml/lxml.etree.c:47744)
IndexError: list index out of range
ERROR:django.request:Internal Server Error: /explorer/schema
Traceback (most recent call last):
  File "/Users/sachin_sr/Downloads/yang-explorer-master/v/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/views.py", line 281, in schema_handler
    return get_schema(request, req)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/utils/schema.py", line 78, in get_schema
    sclist = xml[0][0][0][0]
  File "lxml.etree.pyx", line 1098, in lxml.etree._Element.__getitem__ (src/lxml/lxml.etree.c:47744)
IndexError: list index out of range
[25/Jul/2016 23:48:17]"GET /explorer/schema?&action=get%2Dschema&payload=%3Cpayload%20version%3D%223%22%20protocol%3D%22netconf%22%3E%0A%20%20%3Cmetadata%3E%0A%20%20%20%20%3Cdevice%2Dauth%20profile%3D%22%22%20platform%3D%22csr%22%20host%3D%22%22%20port%3D%22%22%20user%3D%22%22%20passwd%3D%22%22%2F%3E%0A%20%20%20%20%3Cnetconf%2Dauth%20host%3D%2210%2E202%2E10%2E49%22%20port%3D%22830%22%20user%3D%22root%22%20passwd%3D%22sitlab123%21%22%2F%3E%0A%20%20%3C%2Fmetadata%3E%0A%20%20%3Ckeyvalue%2F%3E%0A%3C%2Fpayload%3E HTTP/1.1" 500 82656
 ------------------------------------------------------------------------------------------------------------------

**Comment by pgohite** [comment]
Yes it should work with any netconf agent. However we have not tested against Junos devices. Please see which device type works with Junos (most likely 'junos')

Please see if below script work against your device, this script has device_params as 'junos'. If this works we may be able to add new device (platform) types to yang-explorer.
 
```
"""
    Netconf python example by yang-explorer (https://github.com/CiscoDevNet/yang-explorer)

    Installing python dependencies:
    > pip install lxml ncclient

    Running script: (save as example.py)
    > python example.py -a <address> -u <username> -p <password> --port 
"""

from argparse import ArgumentParser
from ncclient import manager
from ncclient.operations import RPCError

if __name__ == '__main__':

    parser = ArgumentParser(description='Usage:')

    # script arguments
    parser.add_argument('-a', '--host', type=str, required=True,
                        help="Device IP address or Hostname")
    parser.add_argument('-u', '--username', type=str, required=True,
                        help="Device Username (netconf agent username)")
    parser.add_argument('-p', '--password', type=str, required=True,
                        help="Device Password (netconf agent password)")
    parser.add_argument('--port', type=int, default=830,
                        help="Netconf agent port")
    args = parser.parse_args()

    # connect to netconf agent
    with manager.connect(host=args.host,
                         port=args.port,
                         username=args.username,
                         password=args.password,
                         timeout=90,
                         hostkey_verify=False,
                         device_params={'name': 'junos'}) as m:

        # execute netconf operation
        for c in m.server_capabilities:
            print c
```

**Comment by sachinsr099** [comment]
Hi pgohite,

Thank you so much for responding. 

When I executed the program:
$python example.py -a 10.102.11.69 -u root -p xxxxxxxx --port 830

This is the Error I got when I tried to execute the script you mentioned.

-------------------------------------------------------------------------------------------------------------------
No handlers could be found for logger "ncclient.transport.ssh"
Traceback (most recent call last):
  File "example.py", line 39, in <module>
    device_params={'name': 'junos'}) as m:
  File "/Users/sachin_sr/PycharmProjects/untitled6/ncclient/manager.py", line 153, in connect
    return connect_ssh(*args, **kwds)
  File "/Users/sachin_sr/PycharmProjects/untitled6/ncclient/manager.py", line 118, in connect_ssh
    session.connect(*args, **kwds)
  File "/Users/sachin_sr/PycharmProjects/untitled6/ncclient/transport/ssh.py", line 377, in connect
    t.start_client()
  File "/Library/Python/2.7/site-packages/paramiko/transport.py", line 493, in start_client
    raise e
RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.
-------------------------------------------------------------------------------------------------------------------
P.S :
1. I updated OpenSSL as well and I have also tried to ssh with device manually and worked with initial hello messages.

**Comment by pgohite** [comment]
So it prints capability finally ? If yes, I will add 'junos' type to list of platforms. Meanwhile you can try using 'csr' as platform and see if that works ?

**Comment by sachinsr099** [comment]
Yes you can.

**Comment by sachinsr099** [comment]
Hi Pgohite,

I Tried after Fix #34 Support for configurable device platforms.

Even though it show the compatibility message.

When I try to fetch Yang Models from device. The same error occurs.

[27/Jul/2016 17:28:21] ERROR [django.request] Internal Server Error: /explorer/schema
Traceback (most recent call last):
  File "/Users/sachin_sr/Downloads/yang-explorer-master/v/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/views.py", line 296, in schema_handler
    return get_schema(request, req)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/utils/schema.py", line 78, in get_schema
    sclist = xml[0][0][0][0]
  File "lxml.etree.pyx", line 1098, in lxml.etree._Element.__getitem__ (src/lxml/lxml.etree.c:47744)
IndexError: list index out of range
ERROR:django.request:Internal Server Error: /explorer/schema
Traceback (most recent call last):
  File "/Users/sachin_sr/Downloads/yang-explorer-master/v/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/views.py", line 296, in schema_handler
    return get_schema(request, req)
  File "/Users/sachin_sr/Downloads/yang-explorer-master/server/explorer/utils/schema.py", line 78, in get_schema
    sclist = xml[0][0][0][0]
  File "lxml.etree.pyx", line 1098, in lxml.etree._Element.__getitem__ (src/lxml/lxml.etree.c:47744)
IndexError: list index out of range
[27/Jul/2016 17:28:22]"GET /explorer/schema?&action=get%2Dschema&payload=%3Cpayload%20version%3D%223%22%20protocol%3D%22netconf%22%3E%0A%20%20%3Cmetadata%3E%0A%20%20%20%20%3Cdevice%2Dauth%20profile%3D%22%22%20platform%3D%22junos%22%20host%3D%22%22%20port%3D%22%22%20user%3D%22%22%20passwd%3D%22%22%2F%3E%0A%20%20%20%20%3Cnetconf%2Dauth%20host%3D%2210%2E202%2E10%2E49%22%20port%3D%22830%22%20user%3D%22root%22%20passwd%3D%22sitlab123%21%22%2F%3E%0A%20%20%3C%2Fmetadata%3E%0A%20%20%3Ckeyvalue%2F%3E%0A%3C%2Fpayload%3E HTTP/1.1" 500 82546

**Comment by pgohite** [comment]
Please verify that get-schema is supported in the device. yang-explorer required get-schema to work in order to sync models from device.

**Comment by sachinsr099** [comment]
I am able to fetch YANG models when I tried to access device directly through SSH.

Here is the link: 
http://www.juniper.net/documentation/en_US/junos15.1/topics/task/operational/netconf-yang-module-obtaining-and-importing.html

**To generate device-specific YANG modules:**
Execute the show system schema operational mode command, and specify the module name, the YANG format, and optionally, a file for the output.

    user@host> show system schema module module-name format yang output-file-name filename

For example, the following command generates a YANG module that defines the device-specific configuration hierarchy and saves it to a file:

   user@host> show system schema module configuration format yang output-file-name /var/tmp/conf

P.S: I just got one yang model i.e., config.yang ( Main Module )

**Comment by ezobn** [comment]
The problem here that Juniper has to support Netconf-monitoring (https://tools.ietf.org/html/rfc6022 <https://tools.ietf.org/html/rfc6022>) to be able to have got Netconf RPC get-scheme working and exposed as capability...
Not just this kind of manual workaround… how to get schemas from device.
_________________________
Regards,
Evgeny Zobnitsev
Moscow, Russia
mobile: +79169125830
e-mail: e@zobnitsev.ru <mailto:e@zobnitsev.ru>
skype: ezobn77
http://eaz.tel <http://eaz.tel/>

**Comment by pgohite** [comment]
Thanks @ezobn.

Yes ietf-netconf-monitoring support is required for automatic model sync from device.  For automatic sync Correct RPC to get list of schema is -

```
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get>
    <filter>
      <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
        <schemas>
          <schema>
            <identifier/>
          </schema>
        </schemas>
      </netconf-state>
    </filter>
  </get>
</rpc>
```

Correct RPC to fetch content of one schema is - 

```
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <get-schema xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
    <identifier>ietf-yang-types</identifier>
  </get-schema>
</rpc>
```

**Alternatively** You can Add yang models to yang-explorer manually using **Manage-Models -> Workspace -> Add**, using this method all required (dependencies) must be uploaded to complete compilation.
