### ISSUE TITLE
Unable to login as guest:guest - unable to open database file

### ISSUE THREAD

**Issue by sankettandulwadkar** [CiscoDevNet/yang-explorer#63]
Hi,

I am trying to use the server to try some RESTconf usage and I get the following error when I try to login -

./start.sh

Starting YangExplorer server ..
Use http://localhost:8088/static/YangExplorer.html

Performing system checks...

System check identified no issues (0 silenced).
May 04, 2017 - 19:49:30
Django version 1.8.3, using settings 'server.settings'
Starting development server at http://localhost:8088/
Quit the server with CONTROL-C.
[04/May/2017 19:49:39]"GET /static/YangExplorer.html HTTP/1.1" 200 6622
[04/May/2017 19:49:39]"GET /static/YangExplorer.html HTTP/1.1" 200 6622
[04/May/2017 19:49:39]"GET /static/history/history.js HTTP/1.1" 304 0
[04/May/2017 19:49:39]"GET /static/history/history.css HTTP/1.1" 304 0
[04/May/2017 19:49:39]"GET /static/swfobject.js HTTP/1.1" 304 0
[04/May/2017 19:49:39]"GET /static/YangExplorer000700.swf HTTP/1.1" 304 0
[04/May/2017 19:49:41]"GET /explorer/session HTTP/1.1" 200 97
[04/May/2017 19:49:58] ERROR [django.request] Internal Server Error: /explorer/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sanket/yang-explorer/server/explorer/views.py", line 68, in login_handler
    login(request, user)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 110, in login
    request.session.cycle_key()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 285, in cycle_key
    self.create()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 41, in create
    self.save(must_create=True)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 65, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: unable to open database file
ERROR:django.request:Internal Server Error: /explorer/login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sanket/yang-explorer/server/explorer/views.py", line 68, in login_handler
    login(request, user)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 110, in login
    request.session.cycle_key()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 285, in cycle_key
    self.create()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 41, in create
    self.save(must_create=True)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 65, in save
    obj.save(force_insert=must_create, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: unable to open database file
[04/May/2017 19:49:58]"POST /explorer/login HTTP/1.1" 500 156270

Can you please help me with this issue?

Thanks!

**Comment by rustogi** [comment]
@sankettandulwadkar 
Have you run "bash setup.sh" in your terminal before issuing "./start.sh"

setup.sh ensures that you use virtualenv and install everything yang explorer needs in that environment.

**Comment by rustogi** [comment]
Unclear if the suggested workflow above addressed the issue. Closing it for now.
