### ISSUE TITLE
Internal Server Error: /explorer/session

### ISSUE THREAD

**Issue by jean-christophe-manciot** [CiscoDevNet/yang-explorer#64]
A lot of errors/exceptions in the log after trying to - unsuccessfully - login as guest/guest:
```
actionmystique@samsung-ubuntu:~/Ansible/yang-explorer$ ./start.sh &
[1] 14135
actionmystique@samsung-ubuntu:~/Ansible/yang-explorer$ 
Activating virtualenv ..
Starting YangExplorer server ..
Use http://localhost:8088/static/YangExplorer.html

Performing system checks...

System check identified no issues (0 silenced).
May 05, 2017 - 16:05:56
Django version 1.8.3, using settings 'server.settings'
Starting development server at http://localhost:8088/
Quit the server with CONTROL-C.
[05/May/2017 16:06:12]"GET /static/YangExplorer.html HTTP/1.1" 200 6622
[05/May/2017 16:06:12]"GET /static/history/history.css HTTP/1.1" 200 1209
[05/May/2017 16:06:12]"GET /static/history/history.js HTTP/1.1" 200 26166
[05/May/2017 16:06:12]"GET /static/swfobject.js HTTP/1.1" 200 10220
[05/May/2017 16:06:12] ERROR [django.request] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/server/urls.py", line 28, in <module>
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/download/', document_root=os.path.join(settings.BASE_DIR,'data'))
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/urls.py", line 20, in <module>
    from explorer import views, profile_view
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/views.py", line 30, in <module>
    from explorer.utils.adapter import Adapter
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/adapter.py", line 25, in <module>
    from explorer.utils.netconf import gen_netconf
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/netconf.py", line 23, in <module>
    from explorer.utils.admin import ModuleAdmin
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/admin.py", line 22, in <module>
    from explorer.utils.yang import Compiler
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/yang.py", line 21, in <module>
    from sets import Set
ImportError: No module named 'sets'
[05/May/2017 16:06:13]"GET /favicon.ico HTTP/1.1" 500 199645
[05/May/2017 16:08:09]"GET /static/YangExplorer.html HTTP/1.1" 200 6622
[05/May/2017 16:08:09] ERROR [django.request] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/server/urls.py", line 28, in <module>
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/download/', document_root=os.path.join(settings.BASE_DIR,'data'))
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/urls.py", line 20, in <module>
    from explorer import views, profile_view
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/views.py", line 30, in <module>
    from explorer.utils.adapter import Adapter
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/adapter.py", line 25, in <module>
    from explorer.utils.netconf import gen_netconf
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/netconf.py", line 23, in <module>
    from explorer.utils.admin import ModuleAdmin
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/admin.py", line 22, in <module>
    from explorer.utils.yang import Compiler
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/yang.py", line 21, in <module>
    from sets import Set
ImportError: No module named 'sets'
[05/May/2017 16:08:09]"GET /favicon.ico HTTP/1.1" 500 199942
[05/May/2017 16:08:09]"GET /static/YangExplorer.html HTTP/1.1" 200 6622
[05/May/2017 16:08:09] ERROR [django.request] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/server/urls.py", line 28, in <module>
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/download/', document_root=os.path.join(settings.BASE_DIR,'data'))
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/urls.py", line 20, in <module>
    from explorer import views, profile_view
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/views.py", line 30, in <module>
    from explorer.utils.adapter import Adapter
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/adapter.py", line 25, in <module>
    from explorer.utils.netconf import gen_netconf
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/netconf.py", line 23, in <module>
    from explorer.utils.admin import ModuleAdmin
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/admin.py", line 22, in <module>
    from explorer.utils.yang import Compiler
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/yang.py", line 21, in <module>
    from sets import Set
ImportError: No module named 'sets'
[05/May/2017 16:08:09]"GET /favicon.ico HTTP/1.1" 500 199942
[05/May/2017 16:08:09]"GET /static/history/history.css HTTP/1.1" 200 1209
[05/May/2017 16:08:09]"GET /static/swfobject.js HTTP/1.1" 200 10220
[05/May/2017 16:08:09]"GET /static/history/history.js HTTP/1.1" 200 26166
[05/May/2017 16:08:09]"GET /static/YangExplorer000700.swf HTTP/1.1" 200 1522025
[05/May/2017 16:08:11] ERROR [django.request] Internal Server Error: /explorer/session
Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/server/urls.py", line 28, in <module>
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/download/', document_root=os.path.join(settings.BASE_DIR,'data'))
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/urls.py", line 20, in <module>
    from explorer import views, profile_view
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/views.py", line 30, in <module>
    from explorer.utils.adapter import Adapter
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/adapter.py", line 25, in <module>
    from explorer.utils.netconf import gen_netconf
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/netconf.py", line 23, in <module>
    from explorer.utils.admin import ModuleAdmin
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/admin.py", line 22, in <module>
    from explorer.utils.yang import Compiler
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/yang.py", line 21, in <module>
    from sets import Set
ImportError: No module named 'sets'
[05/May/2017 16:08:11]"GET /explorer/session HTTP/1.1" 500 200194
[05/May/2017 16:08:19] ERROR [django.request] Internal Server Error: /explorer/login
Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 394, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/server/urls.py", line 28, in <module>
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/download/', document_root=os.path.join(settings.BASE_DIR,'data'))
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/actionmystique/Ansible/yang-explorer/v/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/urls.py", line 20, in <module>
    from explorer import views, profile_view
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/views.py", line 30, in <module>
    from explorer.utils.adapter import Adapter
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/adapter.py", line 25, in <module>
    from explorer.utils.netconf import gen_netconf
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/netconf.py", line 23, in <module>
    from explorer.utils.admin import ModuleAdmin
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/admin.py", line 22, in <module>
    from explorer.utils.yang import Compiler
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/yang.py", line 21, in <module>
    from sets import Set
ImportError: No module named 'sets'
[05/May/2017 16:08:19]"POST /explorer/login HTTP/1.1" 500 200831
```

**Comment by einarnn** [comment]
Jean-Christophe,

What version of Python are you using?

Cheers,

Einar

**Comment by jean-christophe-manciot** [comment]
```
$ python --version
Python 2.7.12+
$ python3 --version
Python 3.5.2+
```

**Comment by rustogi** [comment]
Jean-Christophe,

Could you try the following change to see if using python 2.7.* resolves your issue?

cd yang-explorer
rm -rf v/

Then apply the following one line change to setup.sh.

index c3ca567..b50fd54 100755
--- a/setup.sh
+++ b/setup.sh
@@ -74,7 +74,7 @@ if [[ $NOVENV != 1 ]]; then
     if [ -f "v/bin/activate" ]; then
         source v/bin/activate
     else
-        virtualenv v
+        virtualenv --python=/usr/bin/python2.7 v
         source v/bin/activate
     fi
 fi

Then start explorer again as follows.

bash setup.sh
./start.py

Please let me know if this helps.

Tx

Sudhir

**Comment by jean-christophe-manciot** [comment]
@rustogi 
Yes, the change does allow me to fix this issue.
However, it is a bit strange because the command ```python``` calls python2.7:
```
$ ll /usr/bin/python
lrwxrwxrwx 1 root root 9 Jun  4  2016 /usr/bin/python -> python2.7*
```

**Comment by rustogi** [comment]
@jean-christophe-manciot 
Yes the change was to use python2.7 install inside the virtual environment that is running yang explorer since yang explorer is currently tested to work with python 2.7. 

If you are working on something else on your host machine, just use a different terminal or virtualenv and you should be able to use your preferred python version for other things.

Are you ok if I can work on committing this change?

**Comment by jean-christophe-manciot** [comment]
OK

**Comment by rustogi** [comment]
Great. Tx for verifying. I will work on getting the fix committed.

**Comment by rustogi** [comment]
The resolution of this issues can be tracked via #65

**Comment by afikac** [comment]
Here are some changes required for Python3 to work...   There are probably some more tweaks needed for code to be up to Python3 standards, but this fixes the "sets" module import issue when doing a fresh install with python 3... and the errors that pop up and prevent login button from working with Python3.

>>>  SETS MODULE IMPORT ISSUE
Delete the line  "from sets import Set" on line 21 of ..../yang-explorer/server/explorer/utils/yang.py

>>> PUNCTUATION REQUIRED IN PYTHON 3
Fix issues with "print" parentheses on the following lines...
 
File "..../yang-explorer/server/explorer/utils/ncparse.py", line 61
    print self
Should be
    print(self)

File ".../netmgmt/yang-view/yang-explorer/server/explorer/utils/annotations.py", line 39
    print 'From cache..'
Should be
    print('From cache..')
