### ISSUE TITLE
ERROR:django.request:Internal Server Error: /explorer/schema

### ISSUE THREAD

**Issue by jean-christophe-manciot** [CiscoDevNet/yang-explorer#78]
@rustogi
Latest:
- Ubuntu
- yang explorer
- dependencies
- Target: NX-OSv 9k 7.0(3)I6(1)

Workflow:
- Manage models tab
- device tab
- Select device profile
![select device profile](https://user-images.githubusercontent.com/13176858/30747579-007555e4-9fae-11e7-8f4e-66e9b3152e7c.jpg)

```
[22/Sep/2017 13:51:32] ERROR [django.request] Internal Server Error: /explorer/schema
Traceback (most recent call last):
  File "/home/actionmystique/Ansible/yang-explorer/v/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/views.py", line 297, in schema_handler
    return get_schema(request, req)
  File "/home/actionmystique/Ansible/yang-explorer/server/explorer/utils/schema.py", line 78, in get_schema
    sclist = xml[0][0][0][0]
  File "lxml.etree.pyx", line 1098, in lxml.etree._Element.__getitem__ (src/lxml/lxml.etree.c:47744)
IndexError: list index out of range
```

However, no issue communicating with the target device using the same profile:
- Build tab
- Device settings tab
- Profile: same sa before
- Netconf
- Capabilities
```
urn:ietf:params:netconf:base:1.0
urn:ietf:params:netconf:base:1.1
urn:ietf:params:netconf:capability:candidate:1.0
urn:ietf:params:netconf:capability:confirmed-commit:1.1
urn:ietf:params:netconf:capability:rollback-on-error:1.0
urn:ietf:params:netconf:capability:validate:1.1
urn:ietf:params:netconf:capability:writable-running:1.0

http://cisco.com/ns/yang/cisco-nx-os-device?revision=2017-05-16&amp;module=cisco-nx-os-device&amp;deviations=cisco-nx-os-device-deviations
...
```

**Comment by pgohite** [comment]
Can you please provide full capability statement ?  like you have posted partial one.

**Comment by jean-christophe-manciot** [comment]
It is available in another report [here](https://github.com/YangModels/yang/issues/270).

**Comment by pgohite** [comment]
Looks like device does not support "ietf-netconf-monitoring" which is required to download model from the device. You may try to upload model manually.

**Comment by jean-christophe-manciot** [comment]
I don't think it is possible to upload a model on NX-OSv 9k outside the [list of provided mtx rpms](https://devhub.cisco.com/artifactory/open-nxos-agents/7.0-3-I6-1/x86_64/).

**Comment by pgohite** [comment]
@jean-christophe-manciot  agreed, however we can load feature model in yang explorer (client) manually which are supported by device already if those models are published somewhere. Only automatic sync from device is not possible due to non availability of "ietf-netconf-monitoring".

**Comment by pegah-mnsn** [comment]
my device supports ietf-netconf-monitoring. but still this error occurs while syncing. my device is Junos vsrx 17.3
