### ISSUE TITLE
guest/guest login on OSX with Safari fails

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/yang-explorer#8]
[05/Oct/2015 14:17:11]"GET /static/YangExplorer.html HTTP/1.1" 200 6604
[05/Oct/2015 14:17:11]"GET /static/history/history.css HTTP/1.1" 200 1209
[05/Oct/2015 14:17:11]"GET /static/swfobject.js HTTP/1.1" 200 10220
[05/Oct/2015 14:17:11]"GET /static/history/history.js HTTP/1.1" 200 26166
[05/Oct/2015 14:17:11]"GET /static/YangExplorer.swf HTTP/1.1" 200 2996445
[05/Oct/2015 14:17:12] WARNING [django.request] Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
[05/Oct/2015 14:17:12]"GET /favicon.ico HTTP/1.1" 404 2314
[05/Oct/2015 14:17:13]"GET /explorer/session HTTP/1.1" 200 67
[05/Oct/2015 14:17:36] ERROR [django.request] Internal Server Error: /explorer/login
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nathan/git/yang-explorer/server/explorer/views.py", line 52, in login_handler
    login(request, user)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 110, in login
    request.session.cycle_key()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/base.py", line 285, in cycle_key
    self.create()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 41, in create
    self.save(must_create=True)
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 65, in save
    obj.save(force_insert=must_create, using=using)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: attempt to write a readonly database
ERROR:django.request:Internal Server Error: /explorer/login
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nathan/git/yang-explorer/server/explorer/views.py", line 52, in login_handler
    login(request, user)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 110, in login
    request.session.cycle_key()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/base.py", line 285, in cycle_key
    self.create()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 41, in create
    self.save(must_create=True)
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 65, in save
    obj.save(force_insert=must_create, using=using)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: attempt to write a readonly database
[05/Oct/2015 14:17:37]"POST /explorer/login HTTP/1.1" 500 142905
[05/Oct/2015 14:17:48] ERROR [django.request] Internal Server Error: /explorer/login
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nathan/git/yang-explorer/server/explorer/views.py", line 52, in login_handler
    login(request, user)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 110, in login
    request.session.cycle_key()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/base.py", line 285, in cycle_key
    self.create()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 41, in create
    self.save(must_create=True)
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 65, in save
    obj.save(force_insert=must_create, using=using)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: attempt to write a readonly database
ERROR:django.request:Internal Server Error: /explorer/login
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nathan/git/yang-explorer/server/explorer/views.py", line 52, in login_handler
    login(request, user)
  File "/Library/Python/2.7/site-packages/django/contrib/auth/__init__.py", line 110, in login
    request.session.cycle_key()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/base.py", line 285, in cycle_key
    self.create()
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 41, in create
    self.save(must_create=True)
  File "/Library/Python/2.7/site-packages/django/contrib/sessions/backends/db.py", line 65, in save
    obj.save(force_insert=must_create, using=using)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Library/Python/2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Library/Python/2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: attempt to write a readonly database
[05/Oct/2015 14:17:48]"POST /explorer/login HTTP/1.1" 500 142905

**Comment by NathanDotTo** [comment]
The problem here is that one needs to install as sudo, else the dependencies installs fails, but, by doing so, one ends up creating a database that needs to be accessed as sudo. So, one needs to do this to get the system to work:

sudo ./start.sh

**Comment by einarnn** [comment]
When running setup.sh, it will create and use a virtualenv if you have it installed. This should allow the tool to be installed without root privileges and hence to subsequently be run as a non-root user.

How did you install it?

**Comment by NathanDotTo** [comment]
Hi

I did not use virtualenv, I installed using sudo.

Regards

Nathan
> On 5 Oct 2015, at 17:04, Einar Nilsen-Nygaard <notifications@github.com> wrote:
> 
> When running setup.sh, it will create and use a virtualenv if you have it installed. This should allow the tool to be installed without root privileges and hence to subsequently be run as a non-root user.
> 
> How did you install it?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Nathan John Sowatskey
Programmable Infrastructure, DevOps and SDN
nathan@nathan.to
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net
Google: nathanjohnsowatskey@gmail.com
Skype: nathan_sowatskey
Twitter: NathanDotTo
http://www.kipling.org.uk/poems_if.htm

**Comment by pgohite** [comment]
Hi Nathan,

Does it work when you start with sudo ? If that is the case we just need to document it ?

Thanks,
Pravin

**Comment by NathanDotTo** [comment]
It works when started with sudo.

Regards

Nathan
> On 5 Oct 2015, at 18:30, Pravin Gohite <notifications@github.com> wrote:
> 
> Hi Nathan,
> 
> Does it work when you start with sudo ? If that is the case we just need to document it ?
> 
> Thanks,
> Pravin
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--
Nathan John Sowatskey
Programmable Infrastructure, DevOps and SDN
nathan@nathan.to
www.linkedin.com/in/nathandevops
XMPP: nathandotto@im.koderoot.net
Google: nathanjohnsowatskey@gmail.com
Skype: nathan_sowatskey
Twitter: NathanDotTo
http://www.kipling.org.uk/poems_if.htm

**Comment by pgohite** [comment]
Suggested Changes:

[patch_8.txt](https://github.com/CiscoDevNet/yang-explorer/files/7867/patch_8.txt)

Please let me know if this looks good

Thanks,
Pravin

**Comment by einarnn** [comment]
Hmm. Would it make sense to update setup.sh to only run the parts that need to be run under root privileges if necessary? And to explicitly setup the database, etc., as a non-root user? (Which you can do if you're running under root privileges.)

**Comment by pgohite** [comment]
You mean by individually adding "sudo" to the commands which might require sudo access in setup.py ?

**Comment by einarnn** [comment]
No, I really meant is something like:

* Don't assume it will be run by root or non root
* If run by non-root, then ask, if you get to the commands that require root access without a virtual env, if the user wants to continue, and that if they continue they need to have sudo permissions
* If run by root, then consider asking if the commands that **don't** need root access should be run as an alternate user (e.g. don't create the db that started this thread as the root user unless the runner wants to.

**Comment by pgohite** [comment]
Done
