### ISSUE TITLE
Linux 7.3 : server is not running ERROR

### ISSUE THREAD

**Issue by sreedharbhavanasi** [CiscoDevNet/yang-explorer#90]
Hello,

I am trying to install YANG explorer on my linux box (which is running 7.3 version), installation is success but unable to login into browser (http://localhost:8088/static/YangExplorer.html), Getting  "Server is not running" error. Installed python 2.7 version, PIP 18.1 version and graphviz 2.3x version prior to login.

Here am attaching the log for reference.
---------------
Activating virtualenv ..
Starting YangExplorer server ..
Use http://localhost:8088/static/YangExplorer.html

Performing system checks...

System check identified no issues (0 silenced).
October 08, 2018 - 12:27:45
Django version 1.8.3, using settings 'server.settings'
Starting development server at http://localhost:8088/
Quit the server with CONTROL-C.
[08/Oct/2018 12:28:03]"GET /static/YangExplorer.html HTTP/1.1" 200 6730
[08/Oct/2018 12:28:04]"GET /static/YangExplorer.html HTTP/1.1" 200 6730
[08/Oct/2018 12:28:06] ERROR [django.request] Internal Server Error: /explorer/session
Traceback (most recent call last):
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sbhavana/yang-explorer/server/server/urls.py", line 28, in <module>
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static('/download/', document_root=os.path.join(settings.BASE_DIR,'data'))
  File "/home/sbhavana/yang-explorer/v/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/sbhavana/yang-explorer/server/explorer/urls.py", line 20, in <module>
    from explorer import views, profile_view
  File "/home/sbhavana/yang-explorer/server/explorer/views.py", line 30, in <module>
    from explorer.utils.adapter import Adapter
  File "/home/sbhavana/yang-explorer/server/explorer/utils/adapter.py", line 25, in <module>
    from explorer.utils.netconf import gen_netconf
  File "/home/sbhavana/yang-explorer/server/explorer/utils/netconf.py", line 23, in <module>
    from explorer.utils.admin import ModuleAdmin
  File "/home/sbhavana/yang-explorer/server/explorer/utils/admin.py", line 22, in <module>
    from explorer.utils.yang import Compiler
  File "/home/sbhavana/yang-explorer/server/explorer/utils/yang.py", line 24, in <module>
    from explorer.utils.dygraph import DYGraph
  File "/home/sbhavana/yang-explorer/server/explorer/utils/dygraph.py", line 19, in <module>
    from graphviz import Digraph
ImportError: No module named graphviz
[08/Oct/2018 12:28:07]"GET /explorer/session HTTP/1.1" 500 181459
-----------------

Did am missing something here while installing the YANG explorer on linux machine?

Did any one facing similar issue and any clue on this. 

Thanks in advance.

Sreedhar

**Comment by fallenarc** [comment]
Did you pip install requirements file in the virtual environment?
