### ISSUE TITLE
cannot compile cisco NX-OS 9.2.2 models

### ISSUE THREAD

**Issue by anubisg1** [CiscoDevNet/yang-explorer#93]
when adding cisco yang models, i obtain the following:

ERROR:root:invoke_compile: Compile Errors: ['Traceback (most recent call last):', '  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 420, in <module>', '    run()', '  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 290, in run', '    expect_failure_error=False)', '  File "/home/anubisg1/Desktop/yang-explorer/v/lib/python2.7/site-packages/pyang/__init__.py", line 100, in add_module', '    module.i_adler32 = zlib.adler32(text)', "UnicodeEncodeError: 'ascii' codec can't encode character u'\\xa7' in position 4159: ordinal not in range(128)", '']
Compilation Failed: <messages><message>Traceback (most recent call last):</message><message>  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 420, in &lt;module&gt;</message><message>    run()</message><message>  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 290, in run</message><message>    expect_failure_error=False)</message><message>  File "/home/anubisg1/Desktop/yang-explorer/v/lib/python2.7/site-packages/pyang/__init__.py", line 100, in add_module</message><message>    module.i_adler32 = zlib.adler32(text)</message><message>UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 4159: ordinal not in range(128)</message><message></message></messages>
Cleaning up /home/anubisg1/Desktop/yang-explorer/server/data/session/tmp9yDhSU

**Comment by anubisg1** [comment]
full logs if needed

`ERROR:root:invoke_compile: Compile Errors: ['Traceback (most recent call last):', '  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 420, in <module>', '    run()', '  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 290, in run', '    expect_failure_error=False)', '  File "/home/anubisg1/Desktop/yang-explorer/v/lib/python2.7/site-packages/pyang/__init__.py", line 100, in add_module', '    module.i_adler32 = zlib.adler32(text)', "UnicodeEncodeError: 'ascii' codec can't encode character u'\\xa7' in position 4159: ordinal not in range(128)", '']
Compilation Failed: <messages><message>Traceback (most recent call last):</message><message>  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 420, in &lt;module&gt;</message><message>    run()</message><message>  File "/home/anubisg1/Desktop/yang-explorer/v/bin/pyang", line 290, in run</message><message>    expect_failure_error=False)</message><message>  File "/home/anubisg1/Desktop/yang-explorer/v/lib/python2.7/site-packages/pyang/__init__.py", line 100, in add_module</message><message>    module.i_adler32 = zlib.adler32(text)</message><message>UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 4159: ordinal not in range(128)</message><message></message></messages>
Cleaning up /home/anubisg1/Desktop/yang-explorer/server/data/session/tmp9yDhSU
`

**Comment by anubisg1** [comment]
If it helps, when using a more up to date pyang (version 1.7.8) the error change completely, it looks a bit better to be honest


```
ERROR:root:invoke_compile: Compile Errors: ['data/session/tmpfrj1sQ/Cisco-NX-OS-device.yang:103723: warning: the escape sequence "\\', '" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-if-ip-deviations.yang:79: error: trailing garbage after module', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:9: warning: imported module openconfig-interfaces not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:10: warning: imported module openconfig-routing-policy not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:11: warning: imported module openconfig-ospfv2 not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:12: warning: imported module openconfig-bgp not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:13: warning: imported module openconfig-local-routing not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-deviations.yang:9: warning: imported module openconfig-platform-types not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-deviations.yang:10: warning: imported module openconfig-types not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-linecard-deviations.yang:8: warning: imported module openconfig-platform-linecard not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-transceiver-deviations.yang:9: warning: imported module openconfig-types not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-transceiver-deviations.yang:11: warning: imported module openconfig-interfaces not used', 'data/session/tmpfrj1sQ/cisco-nx-openconfig-relay-agent-deviations.yang:9: warning: imported module openconfig-interfaces not used', 'data/session/tmpfrj1sQ/openconfig-platform-transceiver.yang:485: error: openconfig-platform-port:hardware-port in the path for physical-channel at data/session/tmpfrj1sQ/openconfig-platform-transceiver.yang:479 is not found', '']
Compilation Failed: <messages><message>data/session/tmpfrj1sQ/Cisco-NX-OS-device.yang:103723: warning: the escape sequence "\</message><message>" is unsafe in double quoted strings - pass the flag --lax-quote-checks to avoid this warning</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-if-ip-deviations.yang:79: error: trailing garbage after module</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:9: warning: imported module openconfig-interfaces not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:10: warning: imported module openconfig-routing-policy not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:11: warning: imported module openconfig-ospfv2 not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:12: warning: imported module openconfig-bgp not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-network-instance-deviations.yang:13: warning: imported module openconfig-local-routing not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-deviations.yang:9: warning: imported module openconfig-platform-types not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-deviations.yang:10: warning: imported module openconfig-types not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-linecard-deviations.yang:8: warning: imported module openconfig-platform-linecard not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-transceiver-deviations.yang:9: warning: imported module openconfig-types not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-platform-transceiver-deviations.yang:11: warning: imported module openconfig-interfaces not used</message><message>data/session/tmpfrj1sQ/cisco-nx-openconfig-relay-agent-deviations.yang:9: warning: imported module openconfig-interfaces not used</message><message>data/session/tmpfrj1sQ/openconfig-platform-transceiver.yang:485: error: openconfig-platform-port:hardware-port in the path for physical-channel at data/session/tmpfrj1sQ/openconfig-platform-transceiver.yang:479 is not found</message><message></message></messages>
Cleaning up /home/anubisg1/yang-explorer/server/data/session/tmpfrj1sQ
```
